name: Manasa CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  APP_NAME: ${{ secrets.APP_NAME }}
  DATABASE_URI: ${{ secrets.DATABASE_URI }}
  PORT: 8080
  JWT_ACCESS_TOKEN_SECRET_PRIVATE: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBb1ZEWWVPRW5xTWhUc1VwRjZwWXM1cnc4UmgxdUdTV09sRnc0S1hoMVFtejR0bWJTCm9zUkt3bmh5WmdKb3I0ZjkvMm1vL3dLejc5bjh3VTdqcitBY0s3S1d6a01BTVdZaHZnMW9oWWNzdzlSR25xc1YKMFh2T2h3aEdZcGthaVU2eFhOc3Y4QURMVEJ2eU5INFR5UkRZSk9FNDc3b2ZKckdYN01EVnduc1BEaUxmQ1NZWAp6Ym4ramR0ZnpTNFJzNXJ6Q2I1bFZOUURTUHQyVmFXNkZKVG1pOEdJY3lHK1hEeHV2U3pkVDNSV0dRUlE5UXByCmlYVUpqNjVhR0FZZmxLRzZSU2c2WU1Fa21OL1p6MmVXYzJGbXI0NTBZUWRwb1RRTWhWaEFkUE1PQWlQQ1dHTmwKdXVvOHErSHB2K1kwTmJHU1VRRE92c1pwOEZSeVBaRU5YZ2FNS3dJREFRQUJBb0lCQUVidWRwRUlaOWptWlM2Uwp1eFdBZlRQajF4ajVmZHplejhmYW1QTmJQU3c5SUV1TUFOaURPV0F6ZUJIMHd6VlR0ZExtRWVJM3ZRa2RMKytNCkViL1c2bXdvZGZreUt0YU4wdzV2ZE9NcDRmd2x6ZnVjdk5aRSt6WVM1R2djYkRldCszMGFBQVVuUkQwdUdKME8KUndMbFBqVlJOeWpxRFNLRmVva203WmM3Wnc1T2didjhhOHJBSnBKaVRjdjFUSUlXU3ZwMDdoaFEzclF2cVhWdQpRdkJzeFdheC9VcVg0TTBhbStIenIvYmtZYys4ZGhNS3pPT25VTkIrV1hwTkJNQy80WUtsTFJ4aXB5UlR3a0V3ClB4d2o5dTVBYVNYeXFnL1BFdTI3Q3o3ek5lUFJQR0Q2QnJRVVE4MkdIcVA4TnV2YkhLNXZ0UjA1MUQyQW5QK0EKVTJBQ2hFa0NnWUVBM0M4cnJQRUJUd2UvM3MvMkMwcmJjc3N2cmZZakxKa0tzWlhzNHhlMEdZYmptblNVMUkwMAo4R3lKWk9nRE9nU3pxNE5ZYXM3WlY5VlFXdFgrMzRrQ21mb2ZkOFV6cnZ6WTI2dk03WmttZEJEc21ZRDBxbnVPCmFNdFEyQlYxWUxlQ2k3QVdTZzNwQmNIRUF6NFNZMWhMR0hSeEdBaDFMRDl2Y0UvQVNFOVY4L2NDZ1lFQXU0NU0KQ3RaY2VydUVXeDJtOWJqbDU0VGF4ZTJSRnByR3dzMTFhTjV5QVcycDd3NGhmMmFMaWovbjFLb2FCRjRyMVlrago3NnNXTFlPdjE2WWJhQnpacUg0UzA5aUY2K0NzRUQ2U0IrbTBkU1VuZlBSR3U5SUQ0M05uZWNScCtYTmxTcVRNCkphYTAzcGhleEcvN1FFOCtjUWtGUkI5a3cxbnpuZDhYcVk4OHRHMENnWUFHU3U3VG5YdXRGNHFiUXBSRWxGb2IKT01WZkVtYkU4b2JFdG9VenBFeklZZnVGUVltelhXbkM2VWN2OUJXTGhmRGdtUHRnNmhKNkdTV1h3di9xd1k2cQplZVNHVnNONFg4K096NlVtc1RiUklGNnlzR1hOcllSUGFHZ2lGTkxxOWJPc2JGYm12T2tJK2hXeEJnZ2VnTHA4CnMyODhBWm5mcnR4dmVFZ0ZpUWJxMXdLQmdCREhaeWdsQ3pyem9hQ2hJM21pSS9jMVhIa09pc2RSNjJ3c0EwL3gKYnBPUUl2Nis3ZUkrNDBibjlxNkExVGtFejdrWHZyNUhPUUd6WVR6U29Hc05BYS9nTDRFQ1F1RGFSYXBpWHFBVQptVTlObHAzSUlMZld6d0EvSjhldCtha1dXTDUzeGNlc2hVdlFwOUc5RHVZdThMQWVGWG1Gc1hjRWloWGFpbnhoCjB4VjFBb0dBSU1DSHExRmZXc0dUM0ZIRS9BRWg2Q0dLNSs1cVpIN0RQT3M2TkpnMzdXcitTdmNBVlNDVm9ldTgKTEZnYTRuQm5ZT0s0SWl1c2xkTkUyNUhxWUtEemY4OW1vUWhXVVNIRnVMQ2phMlVTQXFxRk5DS2ZCQSthekFTVAorWncxbTFvdDExdWVRc09jL3ZramFCa05udytNQUIxRXFxQ1gyY0JmYnVQT1VBUVhYd2s9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
  JWT_ACCESS_TOKEN_SECRET_PUBLIC: LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJDZ0tDQVFFQW9WRFllT0VucU1oVHNVcEY2cFlzNXJ3OFJoMXVHU1dPbEZ3NEtYaDFRbXo0dG1iU29zUksKd25oeVpnSm9yNGY5LzJtby93S3o3OW44d1U3anIrQWNLN0tXemtNQU1XWWh2ZzFvaFljc3c5UkducXNWMFh2Twpod2hHWXBrYWlVNnhYTnN2OEFETFRCdnlOSDRUeVJEWUpPRTQ3N29mSnJHWDdNRFZ3bnNQRGlMZkNTWVh6Ym4rCmpkdGZ6UzRSczVyekNiNWxWTlFEU1B0MlZhVzZGSlRtaThHSWN5RytYRHh1dlN6ZFQzUldHUVJROVFwcmlYVUoKajY1YUdBWWZsS0c2UlNnNllNRWttTi9aejJlV2MyRm1yNDUwWVFkcG9UUU1oVmhBZFBNT0FpUENXR05sdXVvOApxK0hwditZME5iR1NVUURPdnNacDhGUnlQWkVOWGdhTUt3SURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run lint --if-present
    - run: npm run build --if-present
    - run: npm run test --if-present
